active_strategy: ma_trend
bollinger_mr:
  default_risk_pct: 0.03
  id: bollinger_mr
  max_positions: 10
  period: 20
  risk_pct: 0.03
  std_dev: 2
  stop_loss_pct: 1.5
  timeframe: 15m
breakout:
  default_risk_pct: 0.03
  gap_pct: 2
  id: breakout
  max_positions: 10
  risk_pct: 0.03
  stop_loss_pct: 2
  take_profit1_pct: 3
  timeframe: 1m
  vol_k: 2
common:
  default_risk_pct: 0.03
  max_positions: 10
  risk_pct: 0.03
ma_trend:
  default_risk_pct: 0.03
  enabled: true
  id: ma_trend
  ma_long: 20
  ma_short: 5
  max_positions: 10
  risk_pct: 0.03
  stop_loss_pct: 2
  take_profit1_pct: 3
  timeframe: 3m
  trail_stop_pct: 1.5
  vol_k: 1.5
system:
  env_type: paper
  market_type: KRX
  scanner_mode: volume
  universe:
  - 005930
  - '000660'
  use_auto_scanner: true
  watchlist_group_code: '000'
vwap_scalping:
  default_risk_pct: 0.03
  enabled: false
  id: vwap_scalping
  max_positions: 10
  risk_pct: 0.03
  take_profit_pct: 1.5
  timeframe: 1m
