active_strategy: ma_trend
bollinger_mr:
  id: bollinger_mr
  max_positions: 10
  period: 20
  risk_pct: 0.03
  std_dev: 2
  stop_loss_pct: 0.015
  timeframe: 15m
breakout:
  gap_pct: 0.02
  id: breakout
  max_positions: 10
  risk_pct: 0.03
  stop_loss_pct: 0.02
  take_profit1_pct: 0.03
  timeframe: 1m
  vol_k: 2
common:
  cross_lookback: 3
  entry_start_time: 091000
  max_positions: 10
  risk_pct: 0.03
  target_weight: 0.1
  trail_activation_pct: 0.03
  whipsaw_threshold: 0.002
database:
  url: postgresql://antistock:antistock@211.188.56.39:5432/antistock
ma_trend:
  enabled: true
  id: ma_trend
  ma_long: 10
  ma_short: 3
  max_positions: 10
  prev_daily_vol_k: 1.5
  risk_pct: 0.03
  stop_loss_pct: 0.02
  take_profit1_pct: 0.03
  timeframe: 5m
  trail_activation_pct: 0.03
  trail_stop_pct: 0.015
  vol_k: 1.5
system:
  env_type: paper
  market_type: KRX
  scanner_mode: volume
  telegram:
    bot_token: 7175981417:AAF58bvA9QvQ_Kpz3pd0PDbH5D79hgenSh8
    chat_id: '7692999971'
    enable_system_alert: true
    enable_trade_alert: true
  tps_limit: 1.5
  tps_server_url: https://tps.bhsong.org
  universe: []
  use_auto_scanner: true
  watchlist_group_code: '000'
vwap_scalping:
  enabled: false
  id: vwap_scalping
  max_positions: 10
  risk_pct: 0.03
  take_profit_pct: 1.5
  timeframe: 1m
